//tealium universal tag - utag.2 ut4.0.201303201957, Copyright 2013 Tealium.com Inc. All Rights Reserved.
var _gaq=_gaq||[];try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1,'link':1};u.domain="battlefield.com";u.prefix="";u.prefix=((u.prefix)?u.prefix+'.':'');u.ga1="UA-28072291-1";u.setallowlinker=true;u.inpage_linkid=false;if(u.inpage_linkid){_gaq.push(['_require','inpage_linkid','//www.google-analytics.com/plugins/ga/inpage_linkid.js'])};_gaq.push([u.prefix+'_setAccount',u.ga1]);_gaq.push([u.prefix+'_setDomainName',(u.domain!=''?u.domain:utag.cfg.domain)]);if(u.setallowlinker||u.domain=='none'){_gaq.push([u.prefix+'_setAllowLinker',true])};u.map={"userid":"cvar1.1","referrerid":"cvar2.2","intcmp":"cvar3.1","userstatus":"cvar5.1","referring-site":"cvar4.1","ga_event_action":"ga_eventAction","ga_event_category":"ga_eventCat","ga_event_label":"ga_eventLabel","ga_event_value":"ga_eventValue"};u.extend=[function(a,b){console.log('tealium.library.media');window.tlm_trackGalleriaSlideshow=function(e){_gaq.push(['_trackEvent',e.v1,e.v2,tlm_getImageName(e.v3)]);console.log('Galleria Slideshow event: '+e.v1+'|'+e.v2+'|'+tlm_getImageName(e.v3));}
window.tlm_trackMediaAsset=function(e){_gaq.push(['_trackEvent',e.v1,e.v2,tlm_getImageName(e.v3)]);console.log('Carousel event: '+e.v1+'|'+e.v2+'|'+tlm_getImageName(e.v3));}
window.tlm_trackAgeGate=function(e){_gaq.push(['_trackEvent','Agegate',e.action,location.href]);console.log('Age Gate: '+e.action+'|'+location.href);}
function tlm_trackCustomAssets(category,action,label){_gaq.push(['_trackEvent',category,action,tlm_getImageName(label)]);console.log('asset tracked: '+category+'|'+action+'|'+tlm_getImageName(label));}
function tlm_getImageName(imgSrc){imgSrc=imgSrc.substring(imgSrc.length,imgSrc.lastIndexOf('/')+1);if(imgSrc.indexOf('?')>-1){imgSrc=imgSrc.substring(0,imgSrc.indexOf('?'));}
return imgSrc;}
jQuery(function(){jQuery('.carousel-container').on('click','.flex-direction-nav a',function(e){var imgSrc=jQuery(this).parents().eq(3).find('.flex-active-slide img').attr('src');var v3=imgSrc;if(jQuery(this).hasClass('flex-prev')){tlm_trackCustomAssets('Carousel','PrevClick',v3);}
else{tlm_trackCustomAssets('Carousel','NextClick',v3);}});jQuery('.carousel-container').find('li').each(function(){jQuery(this).click(function(e){var imgSrc=jQuery(this).parents().eq(3).find('.flex-active-slide img').attr('src');var v3=imgSrc;tlm_trackCustomAssets('Carousel','Pagination',v3);});});jQuery('.carousel-container .slides img').on('click',function(e){var imgSrc=jQuery(this).attr('src');var v3=imgSrc;tlm_trackCustomAssets('Carousel','ImageClick',v3);});jQuery('#ak-screenshots .overlay-screen').on('click',function(e){var imgSrc=jQuery(this).find('img').attr('src');var v3=imgSrc;tlm_trackCustomAssets('Impression','ImageClick',v3);});jQuery('.node-type-close-quarters-page .screen').on('click',function(e){var imgSrc=jQuery(this).find('img').attr('src');var v3=imgSrc;tlm_trackCustomAssets('Impression','ImageClick',v3);});jQuery('.node-type-close-quarters-page .vid').on('click',function(e){var imgSrc=jQuery(this).find('img').attr('src');var v3=imgSrc;tlm_trackCustomAssets('Impression','VideoClick',v3);});jQuery('.carousel-control .buttons').on('click',function(e){var v2;var pag=jQuery(this).parent().find('li.carousel-pagination .pagenum');var pagIndex=jQuery(pag).index(jQuery(pag).parent().find('.active'));var currentCarousel=jQuery(this).parents().eq(3).find('.viewport ul li').get(pagIndex);var imgSrc=jQuery(currentCarousel).find('img').attr('src');var v3=imgSrc;if(jQuery(this).hasClass('carousel-previous')){v2='PrevClick';}
else{v2='NextClick';}
tlm_trackCustomAssets('Carousel',v2,v3);});});},function(a,b){console.log('tealium.library.social');function tlm_trackSocial(category,action){_gaq.push(['_trackSocial',category,action,document.location.href]);console.log('social: '+category+' > '+action+' > '+document.location.href);}
jQuery(document).ready(function(){jQuery('#block--approuting--social-links > ul > li.googleplus').click(function(){tlm_trackSocial('google','follow');});jQuery('#block--approuting--social-links > ul > li.youtube').click(function(){tlm_trackSocial('youtube','follow');});jQuery('#block--approuting--social-links > ul > li.facebook').click(function(){tlm_trackSocial('facebook','follow');});jQuery('#block--approuting--social-links > ul > li.twitter').click(function(){tlm_trackSocial('twitter','follow');});jQuery('#shareme').on('click','li.googlePlus',(function(){tlm_trackSocial('google','+1');}));jQuery('#shareme').on('click','li.reddit',(function(){tlm_trackSocial('reddit','add');}));jQuery('#shareme').on('click','li.facebook',(function(){tlm_trackSocial('facebook','like');}));jQuery('#shareme').on('click','li.twitter',(function(){tlm_trackSocial('twitter','tweet');}));jQuery('#social-feeds > ul > li > a#facebook').click(function(){tlm_trackSocial('facebook','follow');});jQuery('#social-feeds > ul > li > a#twitter').click(function(){tlm_trackSocial('twitter','follow');});jQuery('#social-feeds > ul > li > a#gplus').click(function(){tlm_trackSocial('google','follow');});jQuery('#social-feeds > ul > li > a#youtube').click(function(){tlm_trackSocial('youtube','follow');});jQuery('#social-feeds > ul > li > a#instagram').click(function(){tlm_trackSocial('instagram','follow');});jQuery('a.twitter-share-button').click(function(){tlm_trackSocial('twitter','tweet');});jQuery('#share > #___plusone_0').click(function(){tlm_trackSocial('google','+1');});jQuery('.fb-share-button').click(function(){tlm_trackSocial('facebook','like');});});},function(a,b){console.log('tealium.library.download');function tlm_trackDownload(action,label,href){_gaq.push(['_trackEvent','Download',action,label]);console.log('clicked: '+action+'::'+label);}
window.tlm_extractFilenameFromUrl=function(url){var filename=url;filename=filename.substring(0,(filename.indexOf("#")==-1)?filename.length:filename.indexOf("#"));filename=filename.substring(0,(url.indexOf("?")==-1)?filename.length:filename.indexOf("?"));filename=filename.substring(filename.lastIndexOf("/")+1,filename.length);return filename;};jQuery(document).ready(function(){var urls='/battlefield-1942, /battlefield-2, /battlefield-2142';if(urls.indexOf(location.pathname)>-1){jQuery('h4 > a').click(function(e){tlm_trackDownload('PatchClick',window.tlm_extractFilenameFromUrl(jQuery(this).attr('href')),jQuery(this).attr('href'));setTimeout(function(){},500)});}
urls='/battlefield3/1/prima-guides';if(urls.indexOf(location.pathname)>-1){jQuery('#prima-info').find('a').each(function(){jQuery(this).click(function(e){tlm_trackDownload('PDFClick',window.tlm_extractFilenameFromUrl(jQuery(this).attr('href')),jQuery(this).attr('href'));});});}});},function(a,b){console.log('tealium.library.navigation');function tlm_trackNavigation(action,label){_gaq.push(['_trackEvent','Navigation',action,label]);console.log('tealium.track: '+action+' > '+label);setTimeout(function(){},500);}
jQuery(document).ready(function(){jQuery('#quicklinks').find('li > a').each(function(){jQuery(this).click(function(){tlm_trackNavigation('QuickLinkClick',jQuery(this).html());});});jQuery('#country-selector').find('li > a').each(function(){jQuery(this).click(function(){tlm_trackNavigation('SwitchLocaleClick',jQuery(this).attr('title'));});});jQuery('#block--approuting--sitemenu').find('.parent-menu > li > a').each(function(){jQuery(this).click(function(){tlm_trackNavigation('MainMenuClick',jQuery(this).html());});});jQuery('#block--approuting--sitemenu').find('.child-menu > li > a').each(function(){jQuery(this).click(function(){tlm_trackNavigation('SubMenuClick',jQuery(this).html());});});jQuery('#breadcrumb').find('li > a').each(function(){jQuery(this).click(function(){tlm_trackNavigation('BreadCrumbClick',jQuery(this).html());});});jQuery('#block--approuting--gamelogo > a').click(function(){tlm_trackNavigation('LogoClick','Game Logo');});jQuery('#block--approuting--gus > #logo > a').click(function(){tlm_trackNavigation('LogoClick','EA Logo');});jQuery('#block--approuting--footermenu').find('li > a').each(function(){jQuery(this).click(function(){tlm_trackNavigation('FooterClick',jQuery(this).html());});});});},function(a,b){console.log('tealium.library.retail-links');TTrack={trackEvent:function(obj,v1,v2,v3){if(jQuery(obj).length>0){jQuery(obj).on('click',function(e){_gaq.push(['_trackEvent',v1,v2,v3]);console.log('retail click: '+v3);});}}}
jQuery(function(){TTrack.v1='Retail';TTrack.v2='BuyClick';TTrack.featuredGame='Origin.com-BF3';TTrack.trackEvent(jQuery('.bfportal #block--approuting--gamebuypromo a'),TTrack.v1,TTrack.v2,TTrack.featuredGame);TTrack.trackEvent(jQuery('.bf3 #block--approuting--gamebuypromo a'),TTrack.v1,TTrack.v2,TTrack.featuredGame);TTrack.trackEvent(jQuery('.bf1942 #block--approuting--gamebuypromo a'),TTrack.v1,TTrack.v2,TTrack.featuredGame);TTrack.trackEvent(jQuery('.bfbc #block--approuting--gamebuypromo a'),TTrack.v1,TTrack.v2,TTrack.featuredGame);TTrack.trackEvent(jQuery('.bf2142 #block--approuting--gamebuypromo a'),TTrack.v1,TTrack.v2,'Origin.com-BF2142');TTrack.trackEvent(jQuery('.bf2 #block--approuting--gamebuypromo a'),TTrack.v1,TTrack.v2,'Origin.com-BF2');TTrack.trackEvent(jQuery('.bf3 #usp-container a'),TTrack.v1,TTrack.v2,TTrack.featuredGame);TTrack.trackEvent(jQuery('#armored-kill-wrapper:not(".aftermath-wrapper") #ak-download-callouts li:first'),TTrack.v1,TTrack.v2,'Origin.com-Expansion-ArmoredKill');TTrack.trackEvent(jQuery('#armored-kill-wrapper.aftermath-wrapper #ak-download-callouts li:first'),TTrack.v1,TTrack.v2,'Origin.com-Expansion-AfterMath');TTrack.trackEvent(jQuery('.node-type-back-to-karkand-page #pc-overlay a'),TTrack.v1,TTrack.v2,'Origin.com-Expansion-BackToKarkand');TTrack.trackEvent(jQuery('#cq-download-callouts li:first'),TTrack.v1,TTrack.v2,'Origin.com-Expansion-CloseQuarters');TTrack.trackEvent(jQuery('#kit_2'),TTrack.v1,TTrack.v2,'Origin.com-Shortcut-Kit');TTrack.trackEvent(jQuery('#premium-download-callouts li:first'),TTrack.v1,TTrack.v2,'Origin.com-BF3-Premium-PC-DL');TTrack.trackEvent(jQuery('.node-premium-details-page a.buy-now'),TTrack.v1,TTrack.v2,'Origin.com-BF3-Premium-PC-DL');TTrack.trackEvent(jQuery('.prima-buy-btn'),TTrack.v1,TTrack.v2,'Origin.com-BF3-Prima-Guide');TTrack.trackEvent(jQuery('#bf4-buy-callout a'),TTrack.v1,TTrack.v2,'Origin.com-MOH');jQuery('#btn-search-media-buy').on('click',function(e){var v3,oUrl=jQuery('#search-media-platforms input:checked').val();var pId=oUrl.substring(oUrl.indexOf('productID'),oUrl.indexOf('?'));switch(pId){case'productID.225064100':v3='Origin.com-BF3-PC-DL';break;case'productID.235216600':v3='Origin.com-BF3-PC';break;case'productID.235216800':v3='Origin.com-BF3-Xbox';break;case'productID.235216500':v3='Origin.com-BF3-PS3';break;}
_gaq.push(['_trackEvent',TTrack.v1,TTrack.v2,v3]);console.log('retail click: '+v3);});jQuery('#premium-buy-form').on('submit',function(e){var v3;switch(jQuery(this).find('input:checked').val()){case'PC':v3='Origin.com-BF3-Premium-Ed-PC-DL';break;case'XBOX 360':v3='Origin.com-BF3-Premium-Ed-Xbox';break;case'Playstation 3':v3='Origin.com-BF3-Premium-Ed-PS3';break;}
_gaq.push(['_trackEvent',TTrack.v1,TTrack.v2,v3]);console.log('retail click: '+v3);});$('#mod-buy-game a.external').on('click',function(e){var v3,callout=$(this).attr('href');if(callout.indexOf('origin')>=0){v3='Origin.com-BF3';}
else if(callout.indexOf('ebgames')>=0){v3='EBGames.co.nz-BF3';}
else if(callout.indexOf('jbhifi')>=0){v3='JBHIFIonline.com.au-BF3';}
else if(callout.indexOf('mightyape')>=0){v3='MightyApe.co.nz-BF3';}
if(v3){_gaq.push(['_trackEvent',TTrack.v1,TTrack.v2,v3]);}});});},function(a,b){console.log('tealium.library.externallinks');var tlm_ea_sites=new Array();tlm_ea_sites.push('armyoftwo.com');tlm_ea_sites.push('battlefield.com');tlm_ea_sites.push('battlefieldheroes.com');tlm_ea_sites.push('battleforge.com');tlm_ea_sites.push('commandandconquer.com');tlm_ea_sites.push('crysis.com');tlm_ea_sites.push('deadspace.com');tlm_ea_sites.push('ea.com');tlm_ea_sites.push('ea.onlineregister.com');tlm_ea_sites.push('eafootballworld.com');tlm_ea_sites.push('easports.com');tlm_ea_sites.push('fifauteam.com');tlm_ea_sites.push('lordofultima.com');tlm_ea_sites.push('medalofhonor.com');tlm_ea_sites.push('needforspeed.com');tlm_ea_sites.push('origin.com');tlm_ea_sites.push('play4free.com');tlm_ea_sites.push('pogo.com');tlm_ea_sites.push('simcity.com');tlm_ea_sites.push('swtor.com');tlm_ea_sites.push('thesims.com');tlm_ea_sites.push('thesims3.com');tlm_ea_sites.push('tiberiumalliances.com');tlm_ea_sites.push('warhammeronline.com');function tlm_is_ea_site(domain){for(var i=0;i<tlm_ea_sites.length;i++){if(domain.indexOf(tlm_ea_sites[i])>-1){return true;}}
return false;}
function tlm_trackOutboundLink(target,action){try{_gaq.push(['_trackEvent','Exits',action,target]);console.log("tealium.outboundlink: "+target);}catch(err){}}
function tlm_trackCrossDomainLink(target){try{if(typeof(_gat)=="object"){var pageTracker=_gat._getTrackerByName();var url=pageTracker._getLinkerUrl(target);return url;}}catch(err){return target;}}
jQuery(document).ready(function(){jQuery("a[href],div[data-src]").each(function(){var obj=jQuery(this);if(obj.attr('href')){var href=obj.attr('href');var attributeType='href';}else{var href=obj.attr('data-src');var attributeType='data-src';}
if(href.indexOf('http')>-1){var ea_network=tlm_is_ea_site(href);if(ea_network){obj.click(function(e){tlm_trackOutboundLink(href,'EANetworkClick');if(attributeType=='href'){obj.attr('href',tlm_trackCrossDomainLink(href));}else if(attributeType=='data-src'){obj.attr('data-src',tlm_trackCrossDomainLink(href));}});}else{obj.click(function(e){tlm_trackOutboundLink(href,'ExternalClick');});}}});});},function(a,b){console.log('tealium.library.udo-trigger');if(utag.data.ga_event_category){_gaq.push(['_trackEvent',utag.data.ga_event_category,utag.data.ga_event_action,utag.data.ga_event_label]);}}];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!="undefined"){u.a=a;for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(c in utag.loader.GV(b)){if(typeof u.map[c+":"+b[c]]!="undefined"){b[c+":"+b[c]]=b[c]}}
for(c in utag.loader.GV(b)){if(typeof u.map[c]!="undefined"){d=u.map[c].split(",");for(e=0;e<d.length;e++){if(d[e].indexOf("cvar")>-1){f=d[e].substring(4).split(".");_gaq.push([u.prefix+'_setCustomVar',f[0],((c.indexOf(".")>0)?(c.split("."))[1]:c),b[c],f[1]]);}
else if(d[e].indexOf("EVENT_")==0){b.ga_events=d[e].substring(6).split(";");}
else if(d[e]=="ga_pageOverride"){_gaq.push([u.prefix+'_set',"page",b[c]]);}
else if(d[e]=="ga_accountOverride"){_gaq.push([u.prefix+'_setAccount',b[c]])}
else if(d[e]=="ga_eventAction"){b.ga_eventAction=b[c]}
else if(d[e]=="ga_eventCat"){b.ga_eventCat=b[c]}
else if(d[e]=="ga_eventLabel"){b.ga_eventLabel=b[c]}
else if(d[e]=="ga_eventValue"){b.ga_eventValue=b[c]}
else{_gaq.push([u.prefix+"_set",d[e],b[c]]);}}}}
if(u.a=="view"){_gaq.push([u.prefix+'_trackPageview']);this.clearVar();}
if(typeof b.ga_eventCat!="undefined"&&typeof b.ga_eventAction!="undefined"&&b.ga_eventCat&&b.ga_eventAction){_gaq.push([u.prefix+'_trackEvent',b.ga_eventCat,b.ga_eventAction,(typeof b.ga_eventLabel!="undefined"?b.ga_eventLabel:null),(typeof b.ga_eventValue!="undefined"?parseInt(b.ga_eventValue):null)]);}else if(u.a=="link"&&typeof b.event_name!="undefined"&&typeof b.link_type!="undefined"&&b.event_name&&b.link_type){_gaq.push([u.prefix+'_trackEvent',b.event_name,b.link_type,(typeof b.link_text!="undefined"?b.link_text:null),null]);}
this.clearVar();if(typeof b._corder!="undefined"&&b._corder!=""&&typeof b._cprod!="undefined"&&b._cprod!=""){_gaq.push([u.prefix+'_addTrans',b._corder,b._cstore,b._ctotal,b._ctax,b._cship,b._ccity,b._cstate,b._ccountry]);for(c=0;c<b._cprod.length;c++){if(b._cprod[c]!=""){_gaq.push([u.prefix+'_addItem',b._corder,(typeof b._cprod[c]!="undefined"?b._cprod[c]:""),(typeof b._cprodname[c]!="undefined"?b._cprodname[c]:""),(typeof b._ccat[c]!="undefined"?b._ccat[c]:""),(typeof b._cprice[c]!="undefined"?b._cprice[c]:""),(typeof b._cquan[c]!="undefined"?b._cquan[c]:"1")]);}}
_gaq.push([u.prefix+'_trackTrans']);}
if(typeof b.ga_events!="undefined"){c=b.ga_events;for(f=0;f<4;f++){if(c[f]&&c[f].indexOf("$")==0){c[f]=b[c[f].substring(1)];}c[f]=(typeof c[f]=="undefined")?"":c[f];}if(isNaN(parseInt(c[3])))c[3]=null;_gaq.push([u.prefix+'_trackEvent',c[0],c[1],c[2],c[3]]);this.clearVar();}
(function(){var id='tealium-tag-7001';if(document.getElementById(id)){return;}
var ga=document.createElement('script');ga.type='text/javascript';ga.async=true;ga.id=id;ga.src=('https:'==document.location.protocol?'https://ssl':'http://www')+'.google-analytics.com/ga.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(ga,s);})();}}
try{utag.o[loader].sender[id].clearVar=function(a){for(a=1;a<5;a++){_gaq.push([u.prefix+'_deleteCustomVar',a]);}}}
catch(e){utag.sender[id].clearVar=function(a){for(a=1;a<5;a++){_gaq.push([u.prefix+'_deleteCustomVar',a]);}}};try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('2','ea.ea-battlefieldcom');}catch(e){}
