//tealium universal tag - utag.7 ut4.0.201302052254, Copyright 2013 Tealium.com Inc. All Rights Reserved.
var _gaq=_gaq||[];try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1,'link':1};u.max_custom=10;u.clearVar=function(){for(var i=1;i<=u.max_custom;i++){_gaq.push([u.prefix+'_deleteCustomVar',i])}};u.domain="battlefield.com";u.prefix="eaglobal";u.prefix=((u.prefix)?u.prefix+'.':'');u.ga1="UA-33209435-1";u.setallowlinker=true;u.inpage_linkid=false;if(u.inpage_linkid){_gaq.push(['_require','inpage_linkid','//www.google-analytics.com/plugins/ga/inpage_linkid.js'])};_gaq.push([u.prefix+'_setAccount',u.ga1]);u.anonymizeIp="true";if(u.anonymizeIp==="true"){_gaq.push(['_gat._anonymizeIp'])};_gaq.push([u.prefix+'_setDomainName',(u.domain!=''?u.domain:utag.cfg.domain)]);if(u.setallowlinker||u.domain=='none'){_gaq.push([u.prefix+'_setAllowLinker',true])};u.map={"userid":"cvar1.1","referrerid":"cvar2.2","intcmp":"cvar3.1","referring-site":"cvar4.1","userstatus":"cvar5.1","ga_event_action":"ga_eventAction","ga_event_category":"ga_eventCat","ga_event_label":"ga_eventLabel","ga_event_value":"ga_eventValue"};u.extend=[];u.send=function(a,b,c,d,e,f,g){if(u.ev[a]||typeof u.ev.all!="undefined"){u.a=a;for(c in utag.loader.GV(b)){if(typeof u.map[c+":"+b[c]]!="undefined"){b[c+":"+b[c]]=b[c]}}
for(c in utag.loader.GV(b)){if(typeof u.map[c]!="undefined"){d=u.map[c].split(",");for(e=0;e<d.length;e++){if(d[e].indexOf("cvar")>-1){f=d[e].substring(4).split(".");g=parseInt(f[0]);if(g>u.max_custom){u.max_custom=g};_gaq.push([u.prefix+'_setCustomVar',g,((c.indexOf(".")>0)?(c.split("."))[1]:c),b[c],f[1]])}else if(d[e].indexOf("EVENT_")==0){b.ga_events=d[e].substring(6).split(";");}
else if(d[e]=="ga_pageOverride"){_gaq.push([u.prefix+'_set',"page",b[c]]);}else if(d[e]=="ga_accountOverride"){_gaq.push([u.prefix+'_setAccount',b[c]])}
else if(d[e]=="ga_eventAction"){b.ga_eventAction=b[c]}
else if(d[e]=="ga_eventCat"){b.ga_eventCat=b[c]}
else if(d[e]=="ga_eventLabel"){b.ga_eventLabel=b[c]}
else if(d[e]=="ga_eventValue"){b.ga_eventValue=b[c]}
else if(d[e]=="ga_totalOverride"){b.ga_totalOverride=b[c]}
else{_gaq.push([u.prefix+"_set",d[e],b[c]]);}}}}
if(u.a=="view"){_gaq.push([u.prefix+'_trackPageview']);this.clearVar();}
if(typeof b.ga_eventCat!="undefined"&&typeof b.ga_eventAction!="undefined"&&b.ga_eventCat&&b.ga_eventAction){_gaq.push([u.prefix+'_trackEvent',b.ga_eventCat,b.ga_eventAction,(typeof b.ga_eventLabel!="undefined"?b.ga_eventLabel:null),(typeof b.ga_eventValue!="undefined"?parseInt(b.ga_eventValue):null)]);}else if(u.a=="link"&&typeof b.event_name!="undefined"&&typeof b.link_type!="undefined"&&b.event_name&&b.link_type){_gaq.push([u.prefix+'_trackEvent',b.event_name,b.link_type,(typeof b.link_text!="undefined"?b.link_text:null),null]);}
this.clearVar();if(typeof b._corder!="undefined"&&b._corder!=""&&typeof b._cprod!="undefined"&&b._cprod!=""){_gaq.push([u.prefix+'_addTrans',b._corder,b._cstore,(b.ga_totalOverride?b.ga_totalOverride:b._ctotal),b._ctax,b._cship,b._ccity,b._cstate,b._ccountry]);for(c=0;c<b._cprod.length;c++){if(b._cprod[c]!=""){_gaq.push([u.prefix+'_addItem',b._corder,(typeof b._cprod[c]!="undefined"?b._cprod[c]:""),(typeof b._cprodname[c]!="undefined"?b._cprodname[c]:""),(typeof b._ccat[c]!="undefined"?b._ccat[c]:""),(typeof b._cprice[c]!="undefined"?b._cprice[c]:""),(typeof b._cquan[c]!="undefined"?b._cquan[c]:"1")]);}}
_gaq.push([u.prefix+'_trackTrans']);}
if(typeof b.ga_events!="undefined"){c=b.ga_events;for(f=0;f<4;f++){if(c[f]&&c[f].indexOf("$")==0){c[f]=b[c[f].substring(1)];}c[f]=(typeof c[f]=="undefined")?"":c[f];}if(isNaN(parseInt(c[3])))c[3]=null;_gaq.push([u.prefix+'_trackEvent',c[0],c[1],c[2],c[3]]);this.clearVar();}
(function(){var id='tealium-tag-7001';if(document.getElementById(id)){return;}
var ga=document.createElement('script');ga.type='text/javascript';ga.async=true;ga.id=id;ga.src=('https:'==document.location.protocol?'https://ssl':'http://www')+'.google-analytics.com/ga.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(ga,s);})();}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('7','ea.ea-battlefieldcom');}catch(e){}
